// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSZnijz6yUGS8xuw_SnbdFI2wcsT_KJGo',
    appId: '1:42332107090:web:709ec77a189e1aa8ea8a8b',
    messagingSenderId: '42332107090',
    projectId: 'deliveryapp-3bcee',
    authDomain: 'deliveryapp-3bcee.firebaseapp.com',
    storageBucket: 'deliveryapp-3bcee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQXO_MboOTxwPohMV3aSecez6QWoAJZw',
    appId: '1:42332107090:android:6504e288686757a0ea8a8b',
    messagingSenderId: '42332107090',
    projectId: 'deliveryapp-3bcee',
    storageBucket: 'deliveryapp-3bcee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOup7aSBtVF5QTdOs0FmwFSCKwKkndFqA',
    appId: '1:42332107090:ios:6616fbeccd2aeb61ea8a8b',
    messagingSenderId: '42332107090',
    projectId: 'deliveryapp-3bcee',
    storageBucket: 'deliveryapp-3bcee.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOup7aSBtVF5QTdOs0FmwFSCKwKkndFqA',
    appId: '1:42332107090:ios:6616fbeccd2aeb61ea8a8b',
    messagingSenderId: '42332107090',
    projectId: 'deliveryapp-3bcee',
    storageBucket: 'deliveryapp-3bcee.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSZnijz6yUGS8xuw_SnbdFI2wcsT_KJGo',
    appId: '1:42332107090:web:8f15000ad2730848ea8a8b',
    messagingSenderId: '42332107090',
    projectId: 'deliveryapp-3bcee',
    authDomain: 'deliveryapp-3bcee.firebaseapp.com',
    storageBucket: 'deliveryapp-3bcee.firebasestorage.app',
  );
}
